dataset:
  split_file: /project/hippocampus/common/kaveh/workspace/datasets/splits/dataset_split.csv
  split_name: test
  session_label: "01"
  space: "MNI152"
  pad_mult: 16

  roots:
    HCP_YA: /project/hippocampus/common/kaveh/workspace/datasets/hcpya-u100/derivatives/scpp-preproc-0.1
    OASIS1: /project/hippocampus/common/kaveh/workspace/datasets/oasis-1/derivatives/scpp-preproc-0.1

trainer:
  device: cuda:0
  batch_size: 2
  num_workers: 4

model:
  in_channels: 1
  out_channels: 9
  ckpt_path: /project/hippocampus/common/kaveh/workspace/scpp-runs/seg/exp01_hcpya+oasis1/checkpoints/seg_best_dice.pt

outputs:
  out_roots:
    HCP_YA: /project/hippocampus/common/kaveh/workspace/datasets/hcpya-u100/derivatives/scpp-seg-0.1
    OASIS1: /project/hippocampus/common/kaveh/workspace/datasets/oasis-1/derivatives/scpp-seg-0.1

  log_dir: /project/hippocampus/common/kaveh/workspace/scpp-runs/seg/exp01_hcpya+oasis1/logs_infer_test


hydra:
  run:
    dir: ${outputs.log_dir}
  output_subdir: null
  job:
    chdir: false
